#!/bin/sh

CLX=$(which clang)
if [ "x$CLX" = "x" ]; then
	echo "clang executable not found!"
	exit 1
fi

IDIR=$($CLX -E -v - < /dev/null 2>&1 | grep '^ /' | grep clang | xargs realpath)
> clangdirs.cpp
echo '/**
 *
 *    ######   #######  #     #  #######   #####    #####   #     #  #######  #######   #####   #     #
 *   #     #  #        ##    #  #        #     #  #     #  #     #     #     #        #     #  #     #
 *   #     #  #        # #   #  #        #        #        #     #     #     #        #        #     #
 *  ######   #####    #  #  #  #####     #####   #        #######     #     #####    #        #######
 *  #     #  #        #   # #  #              #  #        #     #     #     #        #        #     #
 * #     #  #        #    ##  #        #     #  #     #  #     #     #     #        #     #  #     #
 * ######   #######  #     #  #######   #####    #####   #     #     #     #######   #####   #     #
 *
 * LLC
 *
 * PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED BY addClangDir.sh
 *
 **/' > clangdirs.cpp
echo '#include <string>' >> clangdirs.cpp
echo '#include <vector>' >> clangdirs.cpp
echo >> clangdirs.cpp
echo 'void addClangDirs(std::vector<std::string> &args)' >> clangdirs.cpp
echo '{' >> clangdirs.cpp
echo '   args.push_back("-idirafter");' >> clangdirs.cpp
echo '   args.push_back("'$IDIR'");' >> clangdirs.cpp
echo '}' >> clangdirs.cpp
echo >> clangdirs.cpp

echo Creating clangdirs.cpp
